apiVersion: v1
kind: ConfigMap
metadata:
  name: scraper-configs
  namespace: crypto-stash
data:
  api-server: http://localhost:80
  pools.json: |
    {
        "ezilpool": [
            { 
                "coin": "eth", 
                "address": "" 
            }
        ]
    }

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper
  namespace: crypto-stash
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 30
      template:
        spec:
          imagePullSecrets:
            - name: registry.cn-shenzhen.aliyuncs.com
          containers:
            - name: scraper
              image: registry.cn-shenzhen.aliyuncs.com/destinesiastudio/crypto-stash-scraper:2.0.0
              args: ["blockchain", "all"]
              env:
                - name: API_SERVER
                  valueFrom:
                    configMapKeyRef:
                      name: staging-configs
                      key: API_SERVER
          restartPolicy: Never